### ISSUE TITLE
PHP version bump

### ISSUE THREAD

**Issue by GawainLynch** [lstrojny/phpunit-function-mocker#6]
We use this library for our unit tests and support PHP >=5.5.9 in line with Symfony/Silex.

So we're wondering if you could tag 28a135419ea174e890e1e6c9ee36f6110e78c78c as 0.3.0 so that we can still run our tests. :smile:

**Comment by lstrojny** [comment]
@GawainLynch of course!

**Comment by lstrojny** [comment]
Tagged as 0.3.0

**Comment by GawainLynch** [comment]
Legendary, thank you very much!
